name: Unit tests

on:
  pull_request: {}

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        kedro_version: ["0.19.7", "0.19.8"]
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync kedro-databricks
        run: |
          uv add "kedro==${{ matrix.kedro_version }}"
          uv sync --no-group test

      - name: Lint kedro-databricks
        run: uv run ruff check

      - name: Test kedro-databricks
        run: uv run pytest tests/unit

      - name: Rename coverage file
        run: mv coverage.junit.xml coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml
          path: coverage-${{ matrix.kedro_version }}-${{ matrix.python-version }}.junit.xml
          if-no-files-found: ignore
  build-pr:
    name: Build PR artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v5
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true

      - name: Create changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: body.md
          push: false

      - name: Create PR artifact
        run: |
          mkdir -p ./pr
          cp -r coverage ./pr/coverage
          cp body.md ./pr/body.md
          cp ${{ github.event_path }} ./pr/event.json
          echo ${{ github.event.pull_request.number }} > ./pr/NR
          ls -la ./pr

      - name: Upload PR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
