name: Unit tests

on:
  pull_request: {}

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        kedro_version: ["0.19.7", "0.19.8"]
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync kedro-databricks
        run: |
          uv sync --dev
          uv add "kedro==${{ matrix.kedro_version }}"
      - name: Lint kedro-databricks
        run: uv run ruff check
      - name: Test kedro-databricks
        run: uv run pytest tests/unit
      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          github-token: ${{ github.token }}
          title: "Unit Test Coverage Report"
          pytest-xml-coverage-path: "coverage.xml"
  version:
    name: Check for changes and post bump comment
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Check Version
        uses: ./.github/actions/check_version
        with:
          github_token: ${{ github.token }}
          push: false
          pr_number: ${{ github.event.pull_request.number }}
